let name;
let customerNumber;
let orderNumber;
let hello = "Hello";
let virtual = "A virtual assistant will assist you soon";
let greeting = "We appreciate your patience";
let wait = ("Let me take a moment to verify the status of order number");
let shipped = ("Your shipment is on its way");
let chatNumber = ("For further inquiries, please use reference chat number ");
let dots = (".  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .");
name = prompt("Please enter your name: ");
customerNumber = prompt("Please enter your 5-digit customer number: ");
orderNumber = prompt("Please enter your 8-digit order number: ");
let firstThree = customerNumber.substring(0,3);
let lastFour = orderNumber.slice(-4);
console.log(hello + "," + " " + name + "." + " " + virtual + ".");
console.log(dots + " ");
console.log(greeting + ".");
console.log(wait + " " + orderNumber + ".");
console.log(dots + " ");
console.log(shipped + ".");
console.log(chatNumber + firstThree + lastFour + ".");
